import blogImage1 from "@assets/blog-quoting-landscaping-jobs.png";
import blogImage2 from "@assets/blog-weekend-enquiries.png";

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  image: string;
  date: string;
  readTime: string;
  author: string;
  authorBio: string;
  content: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "how-to-quote-landscaping-jobs-without-site-visits",
    title: "How to Quote Landscaping Jobs Without Site Visits (And Why You Should)",
    excerpt: "I spent six years running a landscaping business. During those years, I must have done over a thousand site visits. At least 600 of them went absolutely nowhere. There had to be a better way.",
    image: blogImage1,
    date: "28 February 2026",
    readTime: "12 min read",
    author: "Lewis Reid",
    authorBio: "Lewis Reid ran a landscaping business in the UK for six years before building Trade Engine, an AI-powered quoting and design system for landscaping companies.",
    content: [
      `I spent six years running a landscaping business before I built Trade Engine. During those years, I must have done over a thousand site visits. At least 600 of them went absolutely nowhere.`,
      `I'd drive 30 minutes to look at someone's garden, spend an hour measuring and discussing what they wanted, drive home, spend another two hours creating a detailed quote with material breakdowns and labour costs, send it off, and then... nothing. Or worse, I'd get the "it's more than we thought" email three days later.`,
      `The math was brutal. For every 10 site visits, maybe 4 turned into actual jobs. That meant 60% of my time was spent chasing leads who were never going to buy. Either they were just price shopping, had completely unrealistic budgets, or weren't actually serious about moving forward.`,
      `There had to be a better way.`,
      `## The problem with the traditional quoting process`,
      `The standard way landscapers quote jobs hasn't changed in decades. Customer rings you up or fills in a contact form. You schedule a site visit for sometime in the next few days. You drive out to their property, walk around with them for an hour, take measurements, discuss what they're after. Then you go home, create a quote, and send it over.`,
      `The whole process takes about 3-4 hours of your time. And most of the time, you never hear from them again.`,
      `I started tracking this properly in my fourth year of business. Out of every 100 enquiries I got, I'd do about 60 site visits. Of those 60, maybe 25 would turn into actual jobs. That's a 42% conversion rate, which sounds decent until you realise you've just spent 180 hours on work that didn't pay you a penny.`,
      `The worst part? Half those leads were never going to buy from anyone. They just wanted to "see what it would cost" or were gathering quotes to show their partner why they couldn't afford it this year. The other half went with whoever got back to them fastest with a number they could work with.`,
      `## What if you could filter leads before wasting time on them?`,
      `About two years ago, I started experimenting with something different. Instead of scheduling site visits with everyone who enquired, I started asking them to fill in a detailed form on my website first. Garden size, budget range, what they wanted done, style preferences - all of it.`,
      `Then I'd use that information to generate a rough quote and send it back within 24 hours. Not a final number, just a ballpark based on what they'd told me. Something like "Based on a 50 square metre garden with porcelain paving and artificial grass, you're looking at £12,000-15,000."`,
      `The response was interesting. About 40% of people never replied. Those were the ones with £5,000 budgets who wanted £20,000 gardens. I would have wasted hours on those site visits. Another 20% came back saying it was more than expected but asked if there were ways to bring the cost down. Actual conversation starters.`,
      `And the remaining 40%? They said something like "that's in our budget, when can you come and look at it properly?"`,
      `Suddenly I was only doing site visits with people who'd already seen realistic pricing and were still interested. My conversion rate went from 42% to 67%. Same amount of work, way more revenue.`,
      `## How instant quoting actually works`,
      `The system I eventually built for Trade Engine automates what I was doing manually. Customer lands on your website, fills in a form with their garden details - size, budget, what they want done. The system uses your actual pricing (materials plus labour rates you've configured) to generate an itemised quote in about 90 seconds.`,
      `But here's the bit that really changed things: it also creates a photorealistic AI render of what their garden could look like based on the quote. So they're not just seeing numbers, they're seeing what £10,000 actually gets them versus £20,000.`,
      `The quote and the design land in their email inbox while they're still on your website. No waiting three days for you to get back to them. No playing phone tag to schedule a site visit just to get a rough number.`,
      `The ones who see the quote and think "yeah, that's what we're prepared to spend" - those are the ones who book site visits. Everyone else has self-filtered out before you've lifted a finger.`,
      `## "But customers will just use my quote to negotiate with cheaper competitors"`,
      `This is what every landscaper says when I explain this system. I said it myself before I tried it.`,
      `Here's the reality: customers are already getting multiple quotes. They're already comparing you to three or four other landscapers. The question isn't whether they're shopping around - they definitely are. The question is whether you're even in that conversation.`,
      `If you take three days to get back to someone while your competitor quotes them in 90 seconds, you've already lost. They've mentally moved on. They're already talking to the quick responder about site visit dates.`,
      `The instant quote doesn't give away your pricing. It gets you in the game before everyone else has even responded.`,
      `And here's the thing about the AI design: once customers see a photorealistic render of their garden, they stop shopping purely on price. They're buying the vision. They're emotionally invested in that image. The landscaper who just sends numbers can't compete with that.`,
      `## Real numbers from UK landscapers using this approach`,
      `I'm working with a landscaper in Sussex right now who has 82,000 Instagram followers. He was getting hammered with enquiries but half of them were time-wasters. People wanting £3,000 patios when he specialises in £15,000+ full garden transformations.`,
      `He set up an instant quoting system three months ago. Since then:`,
      `- 82% of enquiries now get automatic quotes\n- Site visits are down 40% (he's only meeting qualified leads)\n- His close rate has gone from 40% to 63%\n- He's spending way less time on unpaid work`,
      `Another landscaper I'm talking to in Bristol has 1.75 million followers across TikTok and Instagram. Absolutely massive following. His problem was the opposite - too many enquiries, no way to filter them efficiently. The system lets him pre-qualify by budget automatically. If someone inputs a £5,000 budget, it politely explains his minimum project size. If they're at £20,000+, they get the full quote and design treatment.`,
      `He's basically automated the first stage of his sales process. The leads hitting his phone now are pre-qualified and excited about the design they've already seen.`,
      `## The psychology behind why this works`,
      `Modern customers expect instant responses. They're used to Amazon delivering tomorrow, Uber showing up in five minutes, Google answering their questions in half a second.`,
      `When they fill in an enquiry form for landscaping and don't hear back for three days, they don't think "oh, they must be busy with important work." They think "maybe they're not interested" or "they're probably not very organised."`,
      `The business that responds first - with an actual number, not just "thanks for your enquiry, I'll get back to you" - that business wins about 50% of the time. Regardless of whether they're the cheapest.`,
      `Speed isn't about being desperate or pushy. It's about being there when the customer is ready to make a decision.`,
      `## What about complex projects that need a site visit?`,
      `Fair question. Not every job can be quoted sight unseen. Access issues, ground conditions, existing drainage, levels - there's loads that can only be assessed in person.`,
      `But here's the thing: the instant quote isn't supposed to be your final quote. It's the starting point.`,
      `It shows customers what's realistic based on what they've told you. When you do the site visit, you refine it. Maybe access is tricky so you need to add a day for manual digging. Maybe the ground's solid clay and you need to factor in more hardcore. Maybe they want to upgrade from the porcelain they specified to natural stone.`,
      `The site visit is where you fine-tune the number. But they already know they're in the right ballpark. You're not showing up to someone with a £7,000 budget when your average job is £18,000. That's the time-waster eliminated before you've left the house.`,
      `## How I'd set this up if I was still running my landscaping business`,
      `If I was starting fresh today with what I know now, here's exactly what I'd do:`,
      `First, I'd put a detailed quote form on my website. Garden size, budget, what they want done, style preferences, photos if they have them. Make it easy to fill in - maybe 2 minutes maximum.`,
      `Then I'd connect that to an automated system that uses my actual pricing - what I charge for materials, what my labour rates are, how long different jobs typically take. I'd configure it once with real numbers, not guesses.`,
      `The system would generate an itemised quote based on the customer's input. Supply and fit costs broken down. Then it would create a photorealistic design showing what their garden could look like with those specifications. Both would go to their email in about 90 seconds.`,
      `Every enquiry would also feed into my CRM automatically. Name, email, phone number, what they're after, budget range, the quote they received, the design image - everything in one place.`,
      `Then on Monday morning, I'd review the weekend enquiries. I'd call the ones that match my ideal project profile. "Hi, you got a quote from us on Saturday for the porcelain patio - that's in our sweet spot. When works for you for a site visit?"`,
      `The customer's already seen realistic pricing. They've already got a design they're excited about. The site visit becomes a refinement conversation, not a "let me tell you how much this actually costs" negotiation.`,
      `Conversion rate goes up. Time wasted goes down. Everyone's happier.`,
      `## The tools you need to make this work`,
      `You've got two options really.`,
      `Option one: build it yourself. Set up a pricing calculator on your website, integrate it with a CRM, configure automated emails with the quote attached. If you're technically minded and have 40-60 hours to spare, you can cobble something together for free.`,
      `Option two: use a purpose-built system. There are a few out there now specifically for landscapers. They come with AI design generation, CRM integration, automated email delivery, the works. Setup takes about a week instead of two months. Cost varies but you're typically looking at a few thousand quid for setup plus a couple hundred a month ongoing.`,
      `Either way, the ROI is pretty clear. Let's say you currently do 10 site visits a week at 3 hours each - that's 30 hours. If you can cut that to 6 site visits (the pre-qualified ones) at 3 hours each, you've saved 12 hours a week. That's nearly two full working days you can spend actually doing paid work instead of chasing maybes.`,
      `Over a year, that's about 600 hours saved. If you bill at even £40 an hour, that's £24,000 worth of your time back.`,
      `## Why most landscapers haven't figured this out yet`,
      `The landscaping industry moves slowly when it comes to technology. Most landscapers I know still do quotes in Excel or on the back of an envelope. Half of them don't even have a proper website, just a Facebook page.`,
      `That's actually good news if you're reading this. It means your competitors probably aren't doing this yet. The ones who move first on instant quoting are going to absolutely dominate their local market.`,
      `Customers are already shopping online. They're already comparing multiple landscapers before they make a decision. The ones who can give them information instantly - actual numbers, actual visuals - those are the ones who'll win.`,
      `The technology exists. It works. The question is just whether you'll use it before your competitors figure it out.`,
      `## My honest take after six years in the industry`,
      `I wasted so much time in my early years doing site visits for people who were never going to buy. Driving all over the place, measuring gardens, writing up detailed quotes, sending them off into the void.`,
      `If I'd had instant quoting from day one, I reckon I could have done 30% more actual jobs with the same amount of working hours. Maybe more.`,
      `The landscapers I'm working with now who've switched to this model - they all say the same thing. "Why didn't I do this three years ago?"`,
      `It's not about being impersonal or cutting corners. It's about respecting your time and only spending it on leads who are actually serious. The customers who are ready to move forward don't mind filling in a form to get instant pricing. The ones who just want to "have a look" - well, they've filtered themselves out, and you haven't wasted an afternoon on them.`,
      `If you're still doing it the old way - showing up to every enquiry, quoting everyone, hoping enough of them convert - I'd seriously consider trying something different. Even just for a month. See what happens when you make people tell you their budget upfront before you agree to a site visit.`,
      `Worst case, you go back to the old method. Best case, you get 12 hours a week back and close more jobs with less effort.`,
      `Worth a try, isn't it?`,
      `---`,
      `**Want to see what instant quoting looks like in action?** I built a demo at [premium-landscapes.co.uk](https://www.premium-landscapes.co.uk) - try it as if you're a customer enquiring about landscaping. You'll get a quote and an AI design in about 90 seconds. That's what your customers would experience.`,
    ],
  },
  {
    slug: "why-uk-landscapers-are-losing-60-percent-of-weekend-enquiries",
    title: "Why UK Landscapers Are Losing 60% of Weekend Enquiries (And How to Fix It)",
    excerpt: "62% of landscaping enquiries come in outside business hours. 35% at weekends. If you're not responding until Monday morning, you've already lost most of them to competitors who got there first.",
    image: blogImage2,
    date: "28 February 2026",
    readTime: "14 min read",
    author: "Lewis Reid",
    authorBio: "Lewis Reid ran a UK landscaping business for six years and lost approximately 47 weekend leads before he figured out he needed automation. He now builds instant quoting systems for landscapers who'd quite like to have their weekends back.",
    content: [
      `It's Saturday evening. You're having dinner with your family, properly switched off from work for once. Somewhere across town, a couple is sitting in their garden talking about finally getting that patio done they've been putting off for two years.`,
      `They pull out their phone, Google "landscapers near me," find your website, and fill in your contact form. Budget's realistic. Timeline's flexible. They're ready to move forward.`,
      `What happens next?`,
      `If you're like most landscapers - including how I used to run my business - absolutely nothing. At least not until Monday morning when you're back at your desk checking emails.`,
      `By then, they've already had phone calls from three of your competitors. Two of them have given rough pricing over the phone. One's already booked a site visit for Tuesday.`,
      `You never even got a chance.`,
      `## When customers actually enquire about landscaping`,
      `I started tracking this properly in my third year of running my landscaping business. I was convinced most of my enquiries were coming in during normal working hours - you know, Monday to Friday, 9 to 5, when people had time to ring around during their lunch break.`,
      `Turned out I was completely wrong.`,
      `62% of my enquiries were coming in outside business hours. 35% at weekends. Another 27% on weekday evenings after 6pm. Peak time was Sunday afternoon between 2pm and 5pm, when people were pottering around in their gardens thinking "we really need to sort this out."`,
      `Makes perfect sense when you think about it. When are people at home looking at their outdoor space? Not Tuesday at 11am when they're at work. Saturday afternoon when they're mowing the lawn and thinking about what they'd rather be doing with that space.`,
      `So they grab their phone right then and there. Search for landscapers. Start filling in enquiry forms.`,
      `And then they wait for someone to get back to them.`,
      `## The response time problem`,
      `Here's what I didn't realise for far too long: the first business to respond wins about 50% of the time. Doesn't matter if they're the cheapest. Doesn't matter if they've got the best portfolio. First response wins.`,
      `I found a study on this a few years back - can't remember who did it now - but it tracked enquiries across different trades. Plumbers, electricians, landscapers, the lot. Same pattern every time. The business that got back to the customer first converted at nearly double the rate of everyone else.`,
      `Think about what's happening in the customer's head:`,
      `**Hour 0 (Saturday 8pm):** Really motivated. Excited about the project. Ready to get the ball rolling.`,
      `**Hour 12 (Sunday 8am):** Still keen. Checking emails to see if anyone's got back to them yet.`,
      `**Hour 24 (Monday 8pm):** Talked to two landscapers already. Both seemed decent. Getting quotes from them this week.`,
      `**Hour 48 (Tuesday 8pm):** Got one quote already. Booked site visits with two others. Pretty much decided between those three.`,
      `**Hour 72 (Wednesday 8pm):** You finally email back. Too late mate. They've mentally moved on.`,
      `The customer's excitement has a shelf life. And it's way shorter than most landscapers think.`,
      `## Why I couldn't work weekends (and why you probably can't either)`,
      `Look, I get it. You can't be on call 24/7. I tried that in my first year and nearly had a breakdown. You're running jobs during the week. You've got quotes to write up in the evenings. Weekends are for your family, for actually having a life outside work.`,
      `I wasn't going to start answering enquiry calls at 9pm on a Saturday. That's not sustainable and frankly it's not healthy.`,
      `But here's the thing - your website can work when you can't.`,
      `## The weekend I realised I needed to change something`,
      `This specific Saturday sticks in my mind. I'd had a proper day off - didn't check my work phone once. Went to my kid's football match, had lunch at the pub, came home and watched a film. Lovely day.`,
      `Monday morning I'm going through weekend emails. Seven enquiries. All came in between 10am Saturday and 6pm Sunday. Perfect timing when people are at home thinking about their gardens.`,
      `I responded to all of them first thing Monday. Professional, friendly, asked when I could come and have a look.`,
      `Two responded. Both said they'd already booked site visits with other landscapers but thanks anyway. The other five? Never heard from them again.`,
      `Seven leads. Zero conversions. All because I wasn't working on my day off.`,
      `That felt rubbish. I'd worked hard to get traffic to my website. Those enquiries weren't free - I was paying for Google Ads at the time. And they'd all slipped through my fingers because I had the audacity to have a weekend.`,
      `## What I started doing differently`,
      `I couldn't add more hours to my week. But I could change what happened when someone filled in my enquiry form.`,
      `Instead of just getting an automated "thanks for your enquiry, we'll be in touch soon" email, I set up a system that actually gave them information immediately.`,
      `They'd fill in the form - garden size, budget, what they wanted done. The system would use that information to generate a ballpark quote based on my actual pricing. Not a final number, but realistic. "Based on a 40 square metre garden with porcelain paving and artificial turf, you're looking at £9,000-12,000."`,
      `Then it would create an AI-generated design showing what their garden could look like. Photorealistic render based on the specifications they'd given.`,
      `Quote and design would hit their inbox in about 90 seconds. While they were still on my website.`,
      `Suddenly I was responding to Saturday evening enquiries on Saturday evening. Even though I was at the pub having a pint.`,
      `## The results were honestly a bit mad`,
      `First month I tried this, my weekend conversion rate went from basically zero to about 45%.`,
      `People who enquired on Saturday got a quote and a design immediately. By the time I called them Monday morning, they'd already shown the design to their partner, talked about whether the price was realistic, and decided if they wanted to move forward.`,
      `The conversation changed completely. Instead of "can you come and have a look and give us a rough idea of cost," it was "we got your quote on Saturday, that's within budget, when can you come and fine-tune it?"`,
      `I was only doing site visits with people who'd already seen realistic pricing and were still interested. Conversion rate for those site visits was about 70%. Way higher than the 40-ish percent I'd been getting before.`,
      `Same number of enquiries. Way more actual jobs.`,
      `## "But won't it feel impersonal?"`,
      `Every landscaper asks me this. I asked myself the same question before I set it up.`,
      `Here's the thing though - customers don't want to talk to you at 9pm on Saturday. They don't want to ring you and interrupt your weekend. They just want information.`,
      `They want to know if you can do what they're after and roughly what it'll cost. The instant quote gives them that. Then YOU follow up personally on Monday to have the actual conversation.`,
      `You're not replacing the personal touch. You're capturing the lead so you can have that personal conversation later.`,
      `And honestly? Customers under 50 - which is most of them now - they expect instant responses. They're used to Amazon, used to Uber, used to getting information immediately. Making them wait three days to find out if they can even afford what they want feels slow to them.`,
      `The automated quote isn't impersonal. It's convenient.`,
      `## A landscaper in Bristol with 1.75 million followers`,
      `I'm talking to a bloke at the moment who runs a landscaping business in Bristol. Him and his brother. They've got 790,000 followers on TikTok, over a million on Instagram. Absolutely massive social media presence.`,
      `Their problem was the opposite of not enough enquiries - they were getting hammered with them. DMs, comments, people tagging them in posts. Dozens every single day. Hundreds at weekends when their content was getting the most engagement.`,
      `No way they could respond to all of them personally. Even if they spent every evening just answering messages, they'd fall behind.`,
      `They set up an automated quoting system. Now when someone enquires through their website, they get an instant quote and design. The system filters by budget automatically - if someone's got a £4,000 budget and they specialise in £20,000+ projects, it politely explains their minimum project size.`,
      `The serious leads - the ones with realistic budgets who are actually ready to move forward - those are the only ones that hit their phone now.`,
      `They're not working weekends. They're not staying up till midnight answering DMs. The system does the first-stage filtering for them. They just follow up with the qualified leads on Monday morning.`,
      `## The maths on weekend enquiries`,
      `Let me walk through the numbers as they were for my business. Might be different for yours, but probably not by much.`,
      `**Scenario 1: How I used to do it (no automation)**`,
      `100 weekend enquiries per year. About 2 per weekend, which sounds right.`,
      `I'd respond to them Monday morning. Maybe 30% would reply back - the other 70% had already moved on or gone with someone quicker.`,
      `Of those 30 who replied, about 40% would turn into actual jobs. So 12 jobs total.`,
      `Average job value for me was about £8,000. Total revenue from weekend enquiries: £96,000.`,
      `**Scenario 2: With instant quoting**`,
      `Same 100 weekend enquiries.`,
      `80% get an instant quote and design (the other 20% might not fill in the form properly or want something I don't do).`,
      `50% of those 80 are still engaged when I call Monday - they've seen the quote, they've discussed it with their partner, they're ready to talk about next steps.`,
      `Of those 40, about 50% convert to actual jobs. So 20 jobs.`,
      `Average job value still £8,000. Total revenue from weekend enquiries: £160,000.`,
      `That's an extra £64,000 per year from the same number of enquiries. Just by responding instantly instead of Monday morning.`,
      `And I'm not working weekends. The system is.`,
      `## What about the enquiries that come in at 2am?`,
      `Yeah, you get those too. Someone can't sleep, starts browsing on their phone, ends up on your website at stupid o'clock in the morning.`,
      `Used to drive me mad seeing those come in. By the time I responded the next day, they'd often forgotten they'd even enquired.`,
      `With the automated system, they get their quote and design at 2am. When they wake up Monday morning, it's sitting in their inbox. They think "oh yeah, I looked at landscapers last night - actually got a quote already, let's have a proper look at this."`,
      `Captures leads you'd otherwise lose completely.`,
      `## The competitive advantage nobody's talking about`,
      `Here's what most landscapers don't realise: your competitors probably aren't doing this yet.`,
      `I'd estimate maybe 5% of UK landscaping businesses have automated quoting. Everyone else is still doing it manually. Responding in business hours. Making people wait.`,
      `That's your window.`,
      `Be the first landscaper in your area who responds instantly. Customers will assume you're more professional, more organised, more on top of your business. And they'd be right.`,
      `The ones who move first on this are going to dominate their local market. The ones who wait until everyone's doing it - well, by then it's just table stakes.`,
      `## What I'd tell myself if I could go back five years`,
      `Stop trying to respond to every enquiry personally. You can't work 24/7 and you shouldn't have to.`,
      `Set up a system that handles the first stage for you. Captures the lead details, gives them realistic pricing, shows them what's possible. Then YOU take over for the actual relationship building and quoting refinement.`,
      `Your job as a landscaper is to design and build amazing gardens. Not to sit at your laptop on Sunday evening responding to enquiry forms.`,
      `Automate the stuff that can be automated. Focus your time on the stuff that actually needs you.`,
      `## The tools exist, by the way`,
      `You've got options for setting this up. You can build something yourself if you're technically minded and have time to spare. Set up forms, pricing calculators, automated emails, CRM integration. Probably looking at 40-60 hours of work but you can do it for free.`,
      `Or you use a purpose-built system. There are a few around now specifically for landscapers. AI design generation, CRM integration, automated quote delivery - all of it ready to go. Setup takes about a week instead of two months. Costs a bit obviously, but the ROI is pretty clear when you're converting an extra £64,000 in revenue per year.`,
      `Either way, the technology exists. It works. The question is just whether you'll use it before your competitors figure it out.`,
      `## My honest recommendation`,
      `Try it. Even just for a month.`,
      `Set up some kind of instant response to weekend enquiries. Doesn't have to be a full AI quoting system if that feels like too much. Even just an automated email that says "Thanks for getting in touch. Based on what you've told me, projects like this typically range from £X to £Y. I'll give you a call Monday morning to discuss properly."`,
      `Give them SOMETHING instead of nothing.`,
      `Track what happens to your weekend enquiries before and after. I reckon you'll see a noticeable difference.`,
      `Worst case, you go back to responding Monday morning. Best case, you're converting 30-40% more weekend leads and getting your Sundays back.`,
      `## The bottom line`,
      `You're already losing most of your weekend enquiries. They're slipping through because you're not working when customers are browsing.`,
      `You can either keep losing them, or you can set up something that works on your behalf.`,
      `I spent two years losing weekend leads before I figured this out. Don't make the same mistake I did.`,
      `The customers are enquiring. They're ready to spend money. They just need someone to respond to them when they're actually thinking about it.`,
      `Be that someone. Even when you're not working.`,
      `---`,
      `**Want to see what instant weekend quoting looks like?** Try the demo at [premium-landscapes.co.uk](https://www.premium-landscapes.co.uk) - fill it in as if you're a customer enquiring on a Saturday evening. You'll get a quote and design in 90 seconds. That's what happens when your system works while you're having a day off.`,
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}
