export interface LocationData {
  slug: string;
  name: string;
  region: string;
  context: string;
  gardenType: string;
}

export const locations: LocationData[] = [
  // London & South East
  {
    slug: "london",
    name: "London",
    region: "London & South East",
    context: "London landscapers face the highest competition density in the UK — thousands of companies chasing the same premium garden jobs. Speed wins here: customers who get an instant quote and see their garden visualised move fast, while slow competitors are still arranging site visits.",
    gardenType: "high-value private gardens and commercial courtyards",
  },
  {
    slug: "brighton",
    name: "Brighton",
    region: "London & South East",
    context: "Brighton's affluent homeowners invest heavily in outdoor living spaces, from coastal terraces to lush rear gardens. The city's design-conscious demographic responds exceptionally well to AI visualisation — showing them their finished garden before committing is a powerful differentiator.",
    gardenType: "coastal terraces and contemporary garden designs",
  },
  {
    slug: "eastbourne",
    name: "Eastbourne",
    region: "London & South East",
    context: "Eastbourne has a high proportion of retired homeowners with large gardens and the disposable income to invest in professional landscaping. Automated follow-ups are particularly valuable here — older clients appreciate prompt, professional communication rather than chasing quotes.",
    gardenType: "traditional gardens and seaside lawns",
  },
  {
    slug: "hastings",
    name: "Hastings",
    region: "London & South East",
    context: "Hastings is an emerging market with rapid property regeneration driving demand for garden makeovers. Landscapers who can quote instantly and show customers a visualisation close jobs that used to require multiple site visits.",
    gardenType: "cottage gardens and regenerated urban spaces",
  },
  {
    slug: "canterbury",
    name: "Canterbury",
    region: "London & South East",
    context: "Canterbury's mix of historic properties and modern developments creates strong demand for both traditional and contemporary landscaping. The city's commuter belt population expects fast, digital-first service from all local tradespeople.",
    gardenType: "period property gardens and new-build landscapes",
  },
  {
    slug: "maidstone",
    name: "Maidstone",
    region: "London & South East",
    context: "Maidstone's growing commuter population and thriving property market make it fertile ground for premium landscaping. Homeowners here are aspirational — they want to see exactly what they're getting before they commit.",
    gardenType: "family gardens and patio extensions",
  },
  {
    slug: "medway",
    name: "Medway",
    region: "London & South East",
    context: "The Medway towns are seeing significant regeneration with new housing developments and rising property values. Landscapers who can quote and close jobs digitally are capturing the new wave of homeowners who expect instant service.",
    gardenType: "new-build gardens and urban regeneration projects",
  },
  {
    slug: "guildford",
    name: "Guildford",
    region: "London & South East",
    context: "Guildford is one of the most affluent commuter towns in the UK, with homeowners who have both the budgets and expectations to match. A premium digital presence with instant quotes and AI garden designs positions you above the local competition.",
    gardenType: "Surrey Hills gardens and executive home landscapes",
  },
  {
    slug: "woking",
    name: "Woking",
    region: "London & South East",
    context: "Woking's densely populated commuter belt has high landscaping demand from time-poor professionals who make buying decisions quickly. They want a quote, a visual, and a price — online, without waiting for a callback.",
    gardenType: "suburban family gardens and outdoor entertainment spaces",
  },
  {
    slug: "crawley",
    name: "Crawley",
    region: "London & South East",
    context: "Crawley's mix of residential estates and executive homes creates steady demand for landscaping at all price points. AI quoting helps you filter enquiries efficiently — only spending time on customers who can afford your services.",
    gardenType: "residential estate gardens and contemporary outdoor spaces",
  },
  {
    slug: "reading",
    name: "Reading",
    region: "London & South East",
    context: "Reading's tech-industry workforce sets high expectations for digital service. If your website feels outdated compared to other service businesses they use, you lose credibility before the conversation starts. AI-powered quoting matches those expectations.",
    gardenType: "executive home gardens and corporate landscaping",
  },
  {
    slug: "oxford",
    name: "Oxford",
    region: "London & South East",
    context: "Oxford's property market commands some of the highest garden values outside London, with homeowners who research extensively before committing. A professional AI-powered website with instant quotes and visualisation builds the trust needed to win premium jobs.",
    gardenType: "Victorian terraced gardens and academic quarter landscaping",
  },
  {
    slug: "milton-keynes",
    name: "Milton Keynes",
    region: "London & South East",
    context: "Milton Keynes has one of the UK's youngest homeowner demographics, comfortable with digital-first purchasing. Landscapers here compete with national chains that have polished online experiences — you need the same to stay competitive.",
    gardenType: "modern estate gardens and grid-plan outdoor spaces",
  },
  {
    slug: "watford",
    name: "Watford",
    region: "London & South East",
    context: "Watford's London overspill housing and strong rental-to-purchase conversion rate means constant new garden investment. Homeowners making their first major landscape purchase rely heavily on visualisation to feel confident spending.",
    gardenType: "semi-detached gardens and compact outdoor makeovers",
  },
  {
    slug: "luton",
    name: "Luton",
    region: "London & South East",
    context: "Luton's growing housing market and rising aspiration among homeowners is creating real demand for professional landscaping. A digital-first presence helps you stand out against the many informal operators in the local market.",
    gardenType: "residential gardens and functional family outdoor spaces",
  },
  {
    slug: "southend-on-sea",
    name: "Southend-on-Sea",
    region: "London & South East",
    context: "Southend's coastal location and growing property investment mean homeowners are spending serious money on their outdoor spaces. AI visualisation is particularly powerful by the coast — customers love seeing how their garden will look transformed.",
    gardenType: "coastal gardens and seafront property landscapes",
  },
  {
    slug: "basildon",
    name: "Basildon",
    region: "London & South East",
    context: "Basildon's large residential estates generate consistent landscaping demand from homeowners investing in their outdoor space. Automated follow-ups mean you never lose a lead because you were on site when they emailed.",
    gardenType: "estate gardens and back-garden transformations",
  },
  {
    slug: "chelmsford",
    name: "Chelmsford",
    region: "London & South East",
    context: "Chelmsford is one of Essex's most prosperous cities with growing demand for high-quality landscaping. The commuter demographic here expects fast, professional communication — instant quotes remove the biggest friction in the sales process.",
    gardenType: "detached family gardens and premium outdoor rooms",
  },
  {
    slug: "colchester",
    name: "Colchester",
    region: "London & South East",
    context: "Colchester's historic streets and surrounding villages create demand for both period-property landscaping and modern contemporary designs. Showing customers a visualisation before work begins dramatically reduces post-job disputes.",
    gardenType: "heritage property gardens and rural village landscaping",
  },
  {
    slug: "slough",
    name: "Slough",
    region: "London & South East",
    context: "Slough's proximity to the M4 corridor tech hubs means a high concentration of well-paid professionals who research online before buying anything. Your website needs to perform as well as the brands they already trust.",
    gardenType: "suburban home gardens and corporate green spaces",
  },
  // South
  {
    slug: "portsmouth",
    name: "Portsmouth",
    region: "South",
    context: "Portsmouth's naval history and dense urban population mean garden space is precious — homeowners invest significantly in making the most of what they have. AI design visualisation is compelling when customers are spending big on a small space.",
    gardenType: "compact city gardens and terraced house rear yards",
  },
  {
    slug: "southampton",
    name: "Southampton",
    region: "South",
    context: "Southampton's port economy and student population create a two-speed landscaping market: budget garden maintenance and premium property investment. AI quoting helps you instantly qualify which type of customer you're speaking to.",
    gardenType: "residential gardens and waterfront property landscapes",
  },
  {
    slug: "basingstoke",
    name: "Basingstoke",
    region: "South",
    context: "Basingstoke's large corporate estates and surrounding commuter villages are both underserved by premium landscaping. A professional AI-powered website signals the level of service these homeowners expect to pay for.",
    gardenType: "executive new-builds and Hampshire village gardens",
  },
  {
    slug: "salisbury",
    name: "Salisbury",
    region: "South",
    context: "Salisbury's affluent rural catchment and historic city centre attract homeowners with high garden budgets and high standards. Detailed AI visualisations help them commit to premium projects they might otherwise delay.",
    gardenType: "cathedral city gardens and Wiltshire country properties",
  },
  {
    slug: "bournemouth",
    name: "Bournemouth",
    region: "South",
    context: "Bournemouth's retirement and holiday property market generates year-round landscaping demand. Older, affluent homeowners appreciate a professional digital presence — it builds the trust needed to win projects from clients who won't compromise on quality.",
    gardenType: "coastal retirement gardens and beach-house outdoor spaces",
  },
  {
    slug: "poole",
    name: "Poole",
    region: "South",
    context: "Poole Harbour's millionaire's row and surrounding premium residential areas represent some of the highest landscaping budgets outside London. Your digital first impression must match the standard these clients expect.",
    gardenType: "waterfront luxury gardens and premium coastal properties",
  },
  {
    slug: "bath",
    name: "Bath",
    region: "South",
    context: "Bath's Georgian architecture and UNESCO World Heritage status attract homeowners who care deeply about aesthetics. AI garden visualisation is exceptionally persuasive here — showing customers how their period property garden will look transformed is a genuine sales tool.",
    gardenType: "Georgian period gardens and townhouse outdoor spaces",
  },
  {
    slug: "swindon",
    name: "Swindon",
    region: "South",
    context: "Swindon's large new-build estates and corporate sector create steady landscaping demand from first-time garden investors. AI quoting takes the fear out of getting a quote — customers feel informed rather than pressured.",
    gardenType: "new-estate gardens and semi-detached home landscapes",
  },
  // South West
  {
    slug: "bristol",
    name: "Bristol",
    region: "South West",
    context: "Bristol's affluent professional population and thriving creative scene mean homeowners have both the budget and taste for premium landscaping. The city's tech-forward culture means they expect digital-first service from every contractor they hire.",
    gardenType: "Victorian terrace gardens and contemporary urban spaces",
  },
  {
    slug: "plymouth",
    name: "Plymouth",
    region: "South West",
    context: "Plymouth's naval heritage and coastal location create demand for low-maintenance but beautiful outdoor spaces that withstand the southwest weather. Instant quotes remove the barrier that stops many customers from even starting the conversation.",
    gardenType: "coastal gardens and practical family outdoor spaces",
  },
  {
    slug: "exeter",
    name: "Exeter",
    region: "South West",
    context: "Exeter's university city vibe and growing young professional population are driving demand for design-led landscaping. AI garden visualisation is particularly persuasive with this demographic — they want to see exactly what they're getting.",
    gardenType: "contemporary city gardens and Devon property landscapes",
  },
  {
    slug: "gloucester",
    name: "Gloucester",
    region: "South West",
    context: "Gloucester's mix of historic city centre and growing residential developments creates varied landscaping demand. Automated follow-ups are crucial in this market where customers often enquire with multiple landscapers before deciding.",
    gardenType: "traditional English gardens and Cotswold-adjacent properties",
  },
  {
    slug: "cheltenham",
    name: "Cheltenham",
    region: "South West",
    context: "Cheltenham is home to some of the most affluent households in the UK outside London, with Regency properties and high garden budgets to match. Premium AI-powered presentation helps you command premium prices and attract the best clients.",
    gardenType: "Regency townhouse gardens and premium Cotswold properties",
  },
  // East
  {
    slug: "ipswich",
    name: "Ipswich",
    region: "East",
    context: "Ipswich's growing property market and surrounding Suffolk countryside create strong demand for both residential and rural landscaping. Fast quoting and visualisation tools give you a clear edge over local competitors still relying on phone-first processes.",
    gardenType: "Suffolk countryside gardens and residential townscapes",
  },
  {
    slug: "norwich",
    name: "Norwich",
    region: "East",
    context: "Norwich's independent city culture and creative economy attract homeowners with high aesthetic standards and the budgets to invest in transformative garden projects. AI design visuals help convert the ambitious enquiries into confirmed jobs.",
    gardenType: "Norfolk flint-and-brick gardens and riverside outdoor spaces",
  },
  {
    slug: "peterborough",
    name: "Peterborough",
    region: "East",
    context: "Peterborough's rapid housing growth and expanding commuter population are generating consistent new landscaping demand. Homeowners in new developments want to see their blank-canvas garden transformed — visualisation closes those jobs.",
    gardenType: "new-build estate gardens and Fenland rural properties",
  },
  {
    slug: "cambridge",
    name: "Cambridge",
    region: "East",
    context: "Cambridge's world-renowned academic community and tech corridor attract some of the highest household incomes in the UK. These customers are analytical — they want data (instant quotes) and evidence (visualisations) before making decisions.",
    gardenType: "university city gardens and technology hub corporate spaces",
  },
  {
    slug: "northampton",
    name: "Northampton",
    region: "East",
    context: "Northampton's central location and large residential base create steady landscaping demand from both first-time buyers and established homeowners. AI quoting filters tyre-kickers efficiently so you spend your time on customers ready to buy.",
    gardenType: "Midlands residential gardens and suburban family outdoor spaces",
  },
  {
    slug: "kettering",
    name: "Kettering",
    region: "East",
    context: "Kettering's expanding housing developments and strong local economy are creating new landscaping customers every month. A professional AI-powered website helps position your business above the many informal operators in the area.",
    gardenType: "growing estate gardens and Northamptonshire residential landscapes",
  },
  {
    slug: "bedford",
    name: "Bedford",
    region: "East",
    context: "Bedford's riverside character and strong property market attract homeowners who invest significantly in outdoor space. The town's mix of period properties and modern developments means demand for varied landscaping styles.",
    gardenType: "riverside garden properties and mixed-era residential landscapes",
  },
  // Midlands
  {
    slug: "birmingham",
    name: "Birmingham",
    region: "Midlands",
    context: "Birmingham's vast residential spread and growing middle-class suburbs are generating enormous landscaping demand. In a city this large, being first to respond with a professional quote and garden visual wins jobs that competitors never even get to discuss.",
    gardenType: "suburban family gardens and regenerated city-fringe outdoor spaces",
  },
  {
    slug: "coventry",
    name: "Coventry",
    region: "Midlands",
    context: "Coventry's City of Culture legacy and growing property investment are driving up standards across all home service industries. Landscapers who match that ambition with a professional digital presence win the premium contracts.",
    gardenType: "residential gardens and regenerated urban outdoor spaces",
  },
  {
    slug: "leicester",
    name: "Leicester",
    region: "Midlands",
    context: "Leicester's diverse, entrepreneurial population and thriving residential property market create strong landscaping demand. Homeowners here are value-conscious but willing to invest in quality when the case is made clearly upfront.",
    gardenType: "mixed residential gardens and city suburban outdoor spaces",
  },
  {
    slug: "nottingham",
    name: "Nottingham",
    region: "Midlands",
    context: "Nottingham's large homeowner population and growing prosperity in the West Bridgford and Mapperley areas mean increasing budgets for premium garden work. AI visualisation helps customers feel confident investing in larger projects.",
    gardenType: "East Midlands residential gardens and period property landscapes",
  },
  {
    slug: "derby",
    name: "Derby",
    region: "Midlands",
    context: "Derby's industrial heritage is giving way to residential investment, with homeowners spending more than ever on their outdoor spaces. A fast, professional quoting process positions you ahead of slower local competitors.",
    gardenType: "traditional residential gardens and Derbyshire suburban landscapes",
  },
  {
    slug: "stoke-on-trent",
    name: "Stoke-on-Trent",
    region: "Midlands",
    context: "Stoke's ongoing regeneration and rising homeowner investment create real opportunity for landscapers who can present professionally. In a price-sensitive market, instant transparent quoting builds the trust that converts enquiries into signed jobs.",
    gardenType: "traditional terrace gardens and regeneration-area outdoor spaces",
  },
  {
    slug: "wolverhampton",
    name: "Wolverhampton",
    region: "Midlands",
    context: "Wolverhampton's diverse residential areas and growing investment in the property market are creating new landscaping opportunities. Being first to respond with a clear, professional quote is often all it takes to win the job.",
    gardenType: "Black Country residential gardens and suburban home landscapes",
  },
  {
    slug: "walsall",
    name: "Walsall",
    region: "Midlands",
    context: "Walsall's suburban neighbourhoods and improving property values are driving homeowner investment in outdoor spaces. Digital quoting tools help you compete against larger regional landscaping companies that have a head start on technology.",
    gardenType: "West Midlands suburban gardens and residential outdoor transformations",
  },
  {
    slug: "west-bromwich",
    name: "West Bromwich",
    region: "Midlands",
    context: "West Bromwich's residential estates and growing homeowner population create consistent demand for quality landscaping. AI-powered quoting and automated follow-ups mean you capture every enquiry without extra admin overhead.",
    gardenType: "Black Country estate gardens and family outdoor spaces",
  },
  {
    slug: "dudley",
    name: "Dudley",
    region: "Midlands",
    context: "Dudley's mix of traditional housing stock and newer developments creates varied landscaping demand. Customers who are on the fence about price respond well to seeing a detailed visualisation of their finished garden — it makes the spend feel real and worthwhile.",
    gardenType: "Black Country mixed-era gardens and suburban landscapes",
  },
  {
    slug: "solihull",
    name: "Solihull",
    region: "Midlands",
    context: "Solihull consistently ranks among the most prosperous areas in the Midlands, with large detached homes and high garden budgets. Premium digital presentation through AI quoting and visualisation is essential to attract and retain this calibre of customer.",
    gardenType: "premium detached home gardens and executive property landscapes",
  },
  {
    slug: "worcester",
    name: "Worcester",
    region: "Midlands",
    context: "Worcester's cathedral city setting and prosperous residential catchment attract homeowners who invest in quality garden design. Showing them a finished visual before work begins dramatically increases job values and customer confidence.",
    gardenType: "Worcestershire county gardens and cathedral city outdoor spaces",
  },
  {
    slug: "hereford",
    name: "Hereford",
    region: "Midlands",
    context: "Hereford's rural market town character and surrounding agricultural communities mean customers value both practicality and aesthetics in their gardens. AI quoting helps set realistic expectations upfront, reducing wasted site visits.",
    gardenType: "market town gardens and Herefordshire rural properties",
  },
  {
    slug: "shrewsbury",
    name: "Shrewsbury",
    region: "Midlands",
    context: "Shrewsbury's loop town setting and affluent residential areas attract homeowners with strong aesthetic sensibilities and willingness to invest. A premium digital presence and AI visualisation help you command the premium prices this market supports.",
    gardenType: "Shropshire county gardens and historic town property landscapes",
  },
  {
    slug: "telford",
    name: "Telford",
    region: "Midlands",
    context: "Telford's planned new-town layout includes thousands of family homes with gardens that were designed 40-50 years ago and are due for complete redesign. This represents a huge untapped opportunity for landscapers who can quote and close quickly.",
    gardenType: "new-town estate gardens and Shropshire residential landscapes",
  },
  {
    slug: "corby",
    name: "Corby",
    region: "Midlands",
    context: "Corby's booming population growth and large-scale housing development are creating consistent new landscaping demand. New homeowners need help designing their blank-canvas gardens — AI visualisation makes that decision easy.",
    gardenType: "new development gardens and rapidly growing residential landscapes",
  },
  {
    slug: "nuneaton",
    name: "Nuneaton",
    region: "Midlands",
    context: "Nuneaton's large residential population and improving economic confidence are translating into higher garden investment. Being the landscaper in town with professional digital quoting signals a level of quality that justifies premium pricing.",
    gardenType: "Warwickshire residential gardens and suburban family outdoor spaces",
  },
  {
    slug: "kidderminster",
    name: "Kidderminster",
    region: "Midlands",
    context: "Kidderminster's Worcestershire setting and surrounding affluent villages create a strong market for both residential and rural landscaping. AI quoting removes the awkward price conversation — customers see costs upfront and self-select accordingly.",
    gardenType: "Worcestershire market town gardens and surrounding rural properties",
  },
  // North West
  {
    slug: "manchester",
    name: "Manchester",
    region: "North West",
    context: "Manchester's booming property market and design-led culture mean homeowners have both money and taste to invest in premium outdoor spaces. In a city growing as fast as Manchester, the landscapers who professionalise first capture the best customers.",
    gardenType: "Victorian terrace back gardens and modern city-fringe outdoor spaces",
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    region: "North West",
    context: "Liverpool's property renaissance and growing professional population are driving real investment in outdoor spaces. The city's pride and community culture mean homeowners want their gardens to reflect their success — AI visualisation helps them see that vision.",
    gardenType: "Merseyside residential gardens and regenerated neighbourhood outdoor spaces",
  },
  {
    slug: "salford",
    name: "Salford",
    region: "North West",
    context: "Salford's Media City development and rapid gentrification are attracting high-earning professionals who expect digital-first service from everyone they hire. A smart AI-powered website positions you to serve this growing premium market.",
    gardenType: "MediaCityUK-adjacent gardens and regenerated Salford Quays properties",
  },
  {
    slug: "oldham",
    name: "Oldham",
    region: "North West",
    context: "Oldham's residential communities and improving property confidence are creating new landscaping opportunities. Automated follow-ups mean every enquiry gets a professional response — even the ones that come in on a Sunday evening.",
    gardenType: "Greater Manchester residential gardens and hillside suburban landscapes",
  },
  {
    slug: "bolton",
    name: "Bolton",
    region: "North West",
    context: "Bolton's large residential base and mix of terraced housing and executive areas create landscaping demand at all price points. AI quoting instantly segments customers by budget, so you're spending your time with people who can afford quality work.",
    gardenType: "Lancashire residential gardens and suburban family outdoor spaces",
  },
  {
    slug: "wigan",
    name: "Wigan",
    region: "North West",
    context: "Wigan's homeowner population and improving town centre are driving investment in residential improvement including gardens. A professional AI quote system helps you convert more of the homeowners who are ready to invest but haven't found the right landscaper yet.",
    gardenType: "Greater Manchester estate gardens and terraced property outdoor spaces",
  },
  {
    slug: "blackburn",
    name: "Blackburn",
    region: "North West",
    context: "Blackburn's diverse residential areas and growing investment in home improvement create real landscaping opportunity. Digital-first quoting removes friction for customers who are already researching online at all hours of the day.",
    gardenType: "Lancashire mixed-residential gardens and suburban outdoor spaces",
  },
  {
    slug: "blackpool",
    name: "Blackpool",
    region: "North West",
    context: "Blackpool's mix of tourist economy and permanent residential population creates year-round landscaping demand. Coastal properties and holiday-let owners invest in outdoor spaces that create impact — AI visualisation helps sell the vision.",
    gardenType: "coastal residential gardens and holiday property outdoor spaces",
  },
  {
    slug: "preston",
    name: "Preston",
    region: "North West",
    context: "Preston's university city status and growing professional population mean increasing investment in residential property. Landscapers who can provide a fast, professional digital service are capturing customers before competitors even respond.",
    gardenType: "Lancashire residential gardens and university city outdoor spaces",
  },
  {
    slug: "burnley",
    name: "Burnley",
    region: "North West",
    context: "Burnley's improving property market and growing homeowner confidence are creating new landscaping opportunities in a traditionally under-served market. Being the professional option in a less competitive market means faster growth.",
    gardenType: "East Lancashire residential gardens and traditional mill-town outdoor spaces",
  },
  {
    slug: "chester",
    name: "Chester",
    region: "North West",
    context: "Chester's Roman heritage, beautiful city centre, and affluent surrounding villages attract homeowners with significant garden budgets and high standards. Premium AI-powered presentation helps you win premium contracts in this aspirational market.",
    gardenType: "Cheshire city gardens and surrounding affluent village properties",
  },
  {
    slug: "warrington",
    name: "Warrington",
    region: "North West",
    context: "Warrington's strategic M6/M62 location and growing commuter population create steady landscaping demand. Homeowners here are time-poor professionals who want fast quotes and clear communication — exactly what AI-powered systems deliver.",
    gardenType: "Cheshire commuter town gardens and executive home outdoor spaces",
  },
  // North East
  {
    slug: "newcastle",
    name: "Newcastle upon Tyne",
    region: "North East",
    context: "Newcastle's vibrant property market and growing professional quarter are driving investment in premium residential outdoor spaces. The city's famous community pride means homeowners genuinely care how their garden looks — AI visualisation taps directly into that.",
    gardenType: "Tyneside residential gardens and Northumberland village properties",
  },
  {
    slug: "sunderland",
    name: "Sunderland",
    region: "North East",
    context: "Sunderland's property regeneration and improving economic confidence are creating new homeowner investment in outdoor spaces. Landscapers with a professional digital presence stand out in a market where most competitors still rely on word-of-mouth alone.",
    gardenType: "Wearside residential gardens and regenerated coastal outdoor spaces",
  },
  {
    slug: "middlesbrough",
    name: "Middlesbrough",
    region: "North East",
    context: "Middlesbrough's Teesside regeneration story is translating into real homeowner investment in property improvement. A slick AI-powered quote and design system signals the level of professionalism that premium clients expect.",
    gardenType: "Teesside residential gardens and North Yorkshire peripheral properties",
  },
  {
    slug: "gateshead",
    name: "Gateshead",
    region: "North East",
    context: "Gateshead's MetroCentre catchment and strong residential communities create consistent landscaping demand. Automated follow-up sequences mean you convert more of the enquiries that come in outside your working hours.",
    gardenType: "Tyne and Wear residential gardens and suburban outdoor spaces",
  },
  {
    slug: "durham",
    name: "Durham",
    region: "North East",
    context: "Durham's cathedral city setting and university population attract a mix of affluent long-term residents and young professionals investing in their first properties. AI garden visualisation is a compelling differentiator in this image-conscious market.",
    gardenType: "Durham cathedral city gardens and university area properties",
  },
  // Yorkshire
  {
    slug: "leeds",
    name: "Leeds",
    region: "Yorkshire",
    context: "Leeds is one of the UK's fastest-growing cities, with a booming property market and expanding professional population. Landscapers who invest in AI-powered digital tools now are positioning themselves for long-term dominance in a market growing rapidly.",
    gardenType: "West Yorkshire residential gardens and Harrogate-adjacent executive properties",
  },
  {
    slug: "sheffield",
    name: "Sheffield",
    region: "Yorkshire",
    context: "Sheffield's claim as one of the greenest cities in the UK means residents take their gardens seriously. The city's steel heritage has given way to a creative, design-led culture where homeowners have high aesthetic standards for their outdoor spaces.",
    gardenType: "Sheffield steel-city gardens and Peak District border properties",
  },
  {
    slug: "bradford",
    name: "Bradford",
    region: "Yorkshire",
    context: "Bradford's large residential population and improving property confidence are creating new landscaping opportunities. Fast, transparent AI quoting builds trust in communities where referrals and reputation drive most buying decisions.",
    gardenType: "West Yorkshire residential gardens and Airedale valley outdoor spaces",
  },
  {
    slug: "barnsley",
    name: "Barnsley",
    region: "Yorkshire",
    context: "Barnsley's property regeneration and rising homeowner investment are creating real demand for professional landscaping. A polished AI-powered website positions you as the premium choice in a market where most local operators have no digital presence.",
    gardenType: "South Yorkshire residential gardens and colliery-era renovation outdoor spaces",
  },
  {
    slug: "rotherham",
    name: "Rotherham",
    region: "Yorkshire",
    context: "Rotherham's growing property values and homeowner aspirations are translating into increased landscaping budgets. Being first to respond with a professional quote and garden visual converts the customers who are shopping around.",
    gardenType: "South Yorkshire residential gardens and Don Valley suburban landscapes",
  },
  {
    slug: "doncaster",
    name: "Doncaster",
    region: "Yorkshire",
    context: "Doncaster's improved transport links and growing residential investment make it a strong market for landscaping growth. AI-powered quoting removes the friction that stops many customers from even making an enquiry.",
    gardenType: "South Yorkshire residential gardens and racecourse-adjacent properties",
  },
  {
    slug: "wakefield",
    name: "Wakefield",
    region: "Yorkshire",
    context: "Wakefield's growing cultural quarter and improving property market attract homeowners with rising standards and budgets for outdoor spaces. Premium visualisation and instant quoting help convert aspirational customers into confirmed jobs.",
    gardenType: "West Yorkshire residential gardens and Pennine-edge rural properties",
  },
  {
    slug: "huddersfield",
    name: "Huddersfield",
    region: "Yorkshire",
    context: "Huddersfield's university town character and surrounding Pennine villages create varied landscaping demand from students-turned-homeowners and affluent rural residents. AI quoting serves both markets with transparent, instant pricing.",
    gardenType: "Pennine hillside gardens and Colne Valley residential landscapes",
  },
  {
    slug: "hull",
    name: "Kingston upon Hull",
    region: "Yorkshire",
    context: "Hull's City of Culture legacy and improving residential investment are driving homeowner ambition for better outdoor spaces. A professional AI-powered digital presence gives you credibility in a market where the bar is still relatively low.",
    gardenType: "East Yorkshire residential gardens and Humber estuary outdoor spaces",
  },
  {
    slug: "york",
    name: "York",
    region: "Yorkshire",
    context: "York's medieval city setting and affluent surrounding villages attract homeowners with the highest design standards and budgets to match. AI garden visualisation is a natural fit for customers who want to see exactly how their historic property garden will be transformed.",
    gardenType: "North Yorkshire period gardens and Vale of York rural properties",
  },
  // North West extras
  {
    slug: "stockport",
    name: "Stockport",
    region: "North West",
    context: "Stockport's Cheshire border location and commuter-belt demographics mean high homeowner spending on property improvement. AI quoting and visualisation help you win jobs from the affluent Bramhall and Heald Green market.",
    gardenType: "Greater Manchester/Cheshire border gardens and executive suburban landscapes",
  },
  {
    slug: "lancaster",
    name: "Lancaster",
    region: "North West",
    context: "Lancaster's university city character and surrounding Lancashire countryside attract a mix of academic professionals and rural homeowners. Instant AI quoting removes the geographic friction of serving a spread-out local market efficiently.",
    gardenType: "Lancashire rural gardens and historic city residential outdoor spaces",
  },
  {
    slug: "carlisle",
    name: "Carlisle",
    region: "North West",
    context: "Carlisle's position as Cumbria's largest city and gateway to the Lake District means demand for high-quality garden design from homeowners in some of the UK's most beautiful settings. AI visualisation helps sell the vision of an exceptional outdoor space.",
    gardenType: "Cumbrian residential gardens and Lake District-adjacent rural properties",
  },
  // Scotland
  {
    slug: "glasgow",
    name: "Glasgow",
    region: "Scotland",
    context: "Glasgow's West End and Southside neighbourhoods have some of the most impressive residential gardens in Scotland, with homeowners who invest heavily in outdoor living. Trade Engine's AI quoting and design tools help you win these premium contracts.",
    gardenType: "Glasgow West End tenement gardens and suburban executive landscapes",
  },
  {
    slug: "edinburgh",
    name: "Edinburgh",
    region: "Scotland",
    context: "Edinburgh's New Town and Morningside properties command some of the highest garden values in the UK outside London. Premium AI visualisation and instant quoting position you to serve a client base with both the taste and the budget for exceptional garden design.",
    gardenType: "Edinburgh New Town gardens and Lothians rural properties",
  },
  {
    slug: "aberdeen",
    name: "Aberdeen",
    region: "Scotland",
    context: "Aberdeen's oil industry wealth creates a customer base with high disposable income and high expectations. A professional AI-powered website and instant quoting system signals the premium service level these clients expect to pay for.",
    gardenType: "Granite City residential gardens and Aberdeenshire rural landscapes",
  },
  {
    slug: "dundee",
    name: "Dundee",
    region: "Scotland",
    context: "Dundee's cultural regeneration and growing tech sector are attracting a new wave of young professionals investing in property and outdoor spaces. AI-powered tools appeal directly to this digitally-native customer base.",
    gardenType: "Tayside residential gardens and City of Discovery outdoor spaces",
  },
  {
    slug: "inverness",
    name: "Inverness",
    region: "Scotland",
    context: "Inverness's position as the Highland capital and gateway to some of Scotland's most spectacular scenery creates demand for landscaping that works with the natural environment. AI visualisation helps customers see how their Highland property garden can be transformed.",
    gardenType: "Highland capital gardens and Inverness-shire rural properties",
  },
  {
    slug: "perth",
    name: "Perth",
    region: "Scotland",
    context: "Perth's Fair City setting and prosperous surrounding Perthshire countryside attract homeowners with strong aesthetic sensibilities and garden budgets to match. Instant quoting and professional design visuals help win premium rural and city contracts.",
    gardenType: "Perthshire residential gardens and surrounding rural estate landscapes",
  },
  {
    slug: "stirling",
    name: "Stirling",
    region: "Scotland",
    context: "Stirling's historic castle backdrop and growing commuter-to-Edinburgh population create interesting landscaping demand from history-conscious homeowners and modern professionals alike. AI quoting and design serves both market segments effortlessly.",
    gardenType: "Stirlingshire castle-town gardens and Forth Valley residential landscapes",
  },
  // Wales
  {
    slug: "cardiff",
    name: "Cardiff",
    region: "Wales",
    context: "Cardiff's booming capital city property market and growing professional population are driving real investment in outdoor spaces. AI-powered quoting and design tools position you to win the premium contracts in this fast-growing market.",
    gardenType: "Cardiff Bay gardens and Vale of Glamorgan residential landscapes",
  },
  {
    slug: "swansea",
    name: "Swansea",
    region: "Wales",
    context: "Swansea's coastal setting and Gower Peninsula proximity attract homeowners who want gardens that celebrate their incredible natural surroundings. AI visualisation helps customers see how their outdoor space can reflect the beauty of their location.",
    gardenType: "Swansea Bay gardens and Gower Peninsula coastal properties",
  },
  {
    slug: "newport",
    name: "Newport",
    region: "Wales",
    context: "Newport's proximity to Bristol and Cardiff creates a growing commuter population with urban salaries and Welsh property prices. This combination generates real budget for premium landscaping from homeowners getting more for their money.",
    gardenType: "Gwent residential gardens and Severn Estuary-adjacent outdoor spaces",
  },
  {
    slug: "wrexham",
    name: "Wrexham",
    region: "Wales",
    context: "Wrexham's growing profile following its football club's remarkable story has attracted attention and investment. Homeowners here are investing in their properties with new confidence — landscaping businesses positioned well are seeing real growth.",
    gardenType: "North Wales residential gardens and border country outdoor spaces",
  },
  // Northern Ireland
  {
    slug: "belfast",
    name: "Belfast",
    region: "Northern Ireland",
    context: "Belfast's remarkable regeneration and booming property market have created a confident homeowner class investing seriously in their outdoor spaces. AI-powered quoting and design visualisation helps you win premium garden contracts in a city that's rapidly modernising.",
    gardenType: "Belfast residential gardens and Titanic Quarter-adjacent modern outdoor spaces",
  },
];

export const locationsByRegion = locations.reduce(
  (acc, loc) => {
    if (!acc[loc.region]) acc[loc.region] = [];
    acc[loc.region].push(loc);
    return acc;
  },
  {} as Record<string, LocationData[]>
);

export function getLocation(slug: string): LocationData | undefined {
  return locations.find((l) => l.slug === slug);
}

export const regionOrder = [
  "London & South East",
  "South",
  "South West",
  "East",
  "Midlands",
  "North West",
  "North East",
  "Yorkshire",
  "Scotland",
  "Wales",
  "Northern Ireland",
];
