import { Helmet } from "react-helmet-async";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>Terms of Service | Trade Engine</title>
        <meta name="description" content="Trade Engine terms of service. Important information about our AI-powered landscaping website platform, pricing, and service agreements." />
        <link rel="canonical" href="https://trade-engine.co.uk/terms" />
        <meta name="robots" content="noindex, follow" />
      </Helmet>
      {/* Header */}
      <header className="border-b">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Button variant="ghost" asChild data-testid="button-back-home">
            <Link href="/">
              <ArrowLeft size={18} className="mr-2" />
              Back to Home
            </Link>
          </Button>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
        <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-2">
          Terms of Service
        </h1>
        <p className="text-muted-foreground mb-2">
          Trade Engine
        </p>
        <p className="text-muted-foreground mb-8">
          Last updated: 28 January 2026
        </p>

        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <h2>1. Introduction</h2>
          <p>
            These Terms of Service ("Terms") govern your use of this website, platform, and any related tools, services, or content provided by Trade Engine ("we", "us", "our").
          </p>
          <p>
            By accessing or using this website, you agree to be bound by these Terms. If you do not agree, you must not use this website or any associated services.
          </p>

          <h2>2. Who We Are</h2>
          <p>
            <strong>Trade Engine</strong><br />
            Company registered in England and Wales.<br />
            Registered office: East Midlands, United Kingdom
          </p>
          <p>
            Trade Engine provides software-based tools for indicative landscaping pricing, design visualisations, and customer data capture.
          </p>
          <p><strong>We are not a landscaping contractor.</strong></p>

          <h2>3. Nature of the Service (Important)</h2>
          <p><strong>Our platform provides:</strong></p>
          <ul>
            <li>Indicative landscaping cost estimates</li>
            <li>AI-generated concept designs and visualisations</li>
            <li>Data collection tools for customer requirements</li>
            <li>Storage of submitted information, designs, and quotes</li>
          </ul>
          <p><strong>What the service is NOT:</strong></p>
          <ul>
            <li>A binding quotation</li>
            <li>A final price</li>
            <li>A professional architectural, engineering, or surveying service</li>
            <li>A guarantee of works, materials, availability, or outcomes</li>
          </ul>
          <p>
            <strong>All figures and visuals are estimates and concepts only, intended for guidance and early decision-making.</strong>
          </p>

          <h2>4. No Binding Quotes</h2>
          <p>Any prices shown:</p>
          <ul>
            <li>Are indicative only</li>
            <li>Are based solely on information provided by the user</li>
            <li>May change following site surveys, design revisions, or contractor assessment</li>
          </ul>
          <p>
            Final pricing, timelines, and scope are determined solely by the appointed landscaping contractor.
          </p>
          <p>
            Trade Engine takes no responsibility for final costs agreed between customers and contractors.
          </p>

          <h2>5. Visualisations & AI-Generated Content</h2>
          <p>Designs, images, and layouts generated by the platform:</p>
          <ul>
            <li>Are conceptual representations</li>
            <li>May not reflect real-world constraints</li>
            <li>Are not construction drawings or technical plans</li>
          </ul>
          <p>You acknowledge that:</p>
          <ul>
            <li>Visual outputs are illustrative, not exact</li>
            <li>Final results may differ materially from generated images</li>
          </ul>

          <h2>6. User Responsibilities</h2>
          <p>By using this website, you confirm that:</p>
          <ul>
            <li>Information you provide is accurate to the best of your knowledge</li>
            <li>You understand estimates are non-binding</li>
            <li>You will not rely solely on outputs for financial or construction decisions</li>
          </ul>
          <p>You agree not to:</p>
          <ul>
            <li>Misuse the platform</li>
            <li>Provide false or misleading information</li>
            <li>Attempt to reverse-engineer or exploit the software</li>
            <li>Use the service for unlawful purposes</li>
          </ul>

          <h2>7. Contractors & Third Parties</h2>
          <p>Where we introduce or connect you to third-party landscapers:</p>
          <ul>
            <li>Trade Engine is not a party to any contract</li>
            <li>We do not supervise, control, or guarantee contractors</li>
            <li>Any agreement is strictly between you and the contractor</li>
          </ul>
          <p>We are not liable for:</p>
          <ul>
            <li>Work quality</li>
            <li>Delays</li>
            <li>Disputes</li>
            <li>Pricing changes</li>
            <li>Contractor conduct</li>
          </ul>

          <h2>8. Data Storage & Use</h2>
          <p>By submitting information, you agree that we may:</p>
          <ul>
            <li>Store your data securely</li>
            <li>Share relevant information with approved contractors</li>
            <li>Use anonymised data for analytics and platform improvement</li>
          </ul>
          <p>
            Personal data is handled in accordance with our <Link href="/privacy" className="text-amber-600 hover:text-amber-700">Privacy Policy</Link>.
          </p>

          <h2>9. Intellectual Property</h2>
          <p>
            All content, software, workflows, visuals, and systems on this website are the intellectual property of Trade Engine or its licensors.
          </p>
          <p>You may not:</p>
          <ul>
            <li>Copy or replicate platform functionality</li>
            <li>Redistribute designs or outputs for commercial use</li>
            <li>Use content without permission</li>
          </ul>
          <p>
            Customer-generated inputs remain the property of the customer. Generated outputs remain licensed for personal use only unless otherwise agreed.
          </p>

          <h2>10. Availability & Service Continuity</h2>
          <p>We aim to provide continuous availability but do not guarantee:</p>
          <ul>
            <li>Uninterrupted service</li>
            <li>Error-free operation</li>
            <li>Permanent access to designs or quotes</li>
          </ul>
          <p>We may update, modify, suspend, or withdraw services at any time.</p>

          <h2>11. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Trade Engine shall not be liable for:</p>
          <ul>
            <li>Financial loss</li>
            <li>Loss of profit or opportunity</li>
            <li>Reliance on estimates or visuals</li>
            <li>Errors arising from incorrect user input</li>
            <li>Contractor disputes or outcomes</li>
          </ul>
          <p>
            Our total liability shall not exceed the amount paid (if any) for use of the service.
          </p>

          <h2>12. Indemnity</h2>
          <p>You agree to indemnify Trade Engine against any claims, losses, or liabilities arising from:</p>
          <ul>
            <li>Your misuse of the platform</li>
            <li>Breach of these Terms</li>
            <li>Disputes with contractors</li>
          </ul>

          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by the laws of England and Wales.
            Any disputes shall be subject to the exclusive jurisdiction of the English courts.
          </p>

          <h2>14. Changes to These Terms</h2>
          <p>
            We may update these Terms at any time. Continued use of the website constitutes acceptance of the latest version.
          </p>

          <h2>15. Contact</h2>
          <p>For legal or service enquiries:</p>
          <p>
            Email: <a href="mailto:hello@trade-engine.co.uk">hello@trade-engine.co.uk</a><br />
            Company: Trade Engine
          </p>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t mt-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <p className="text-sm text-muted-foreground text-center">
            © {new Date().getFullYear()} Trade Engine. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
